function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});}

const CHANNEL_POOL=[
 {name:"기묘한 밤",handle:"기묘한밤",category:"mystery",priority:10},
 {name:"디바제시카",handle:"deevajessica",category:"mystery_case",priority:20},
 {name:"돌비공포라디오",handle:"돌비공포라디오",category:"horror",priority:30},
 {name:"별별역사",handle:"별별역사",category:"history_story",priority:40},
 {name:"간다효",handle:"간다효",category:"history_world",priority:50},
 {name:"지식해적단",handle:"studio_pirates",category:"history_knowledge",priority:60},
 {name:"조승연의 탐구생활",handle:"Tamgu",category:"culture_world",priority:70},
 {name:"김지윤의 지식Play",handle:"Kjy_Play",category:"history_world",priority:80},
 {name:"보다 BODA",handle:"보다boda",category:"science_history",priority:90},
 {name:"안될과학",handle:"Unrealscience",category:"science",priority:100},
 {name:"EO",handle:"eoglobal",category:"people_work",priority:110},
 {name:"김진짜 Real KIM",handle:"realkim10",category:"sports_soccer",priority:120},
 {name:"야구부장",handle:"kbonews",category:"sports_baseball",priority:130},
 {name:"달빛뮤즈",handle:"dalbitmuse",category:"movie_story",priority:140},
 {name:"김달",handle:"iamkimdal",category:"relationship",priority:150,shortPick:true}
];

async function yt(env,path,params){const u=new URL(`https://www.googleapis.com/youtube/v3/${path}`);for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v));u.searchParams.set("key",env.YOUTUBE_API_KEY);const r=await fetch(u);const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`YouTube API ${r.status}`);return d;}
function parseDuration(iso){const m=/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/.exec(iso||"");return m?Number(m[1]||0)*86400+Number(m[2]||0)*3600+Number(m[3]||0)*60+Number(m[4]||0):null;}
function gate(title,seconds,category){const t=title||"";if(seconds==null)return{status:"review",reason:"duration_missing",score:null,pool:null};if(/(^|\s|\[|\()#?shorts?($|\s|\]|\))|쇼츠|티저|예고편|하이라이트/i.test(t))return{status:"fail",reason:"short_teaser_highlight",score:0,pool:null};const longPlay=seconds>=3600&&/몰아보기|모음|총정리|FULL|연속|전편|완전판|N편|\d+편/i.test(t);if(longPlay)return{status:"pass",reason:"long_play_compilation",score:88,pool:"60m_plus"};if(seconds>=1200&&seconds<=2400)return{status:"pass",reason:"core_20_40",score:90,pool:"30m"};if(seconds>2400&&seconds<3600)return{status:"review",reason:"40_60_review",score:65,pool:"60m"};if(seconds>=600&&seconds<1200&&category==="relationship")return{status:"pass",reason:"short_pick_exception",score:75,pool:"30m"};if(seconds<1200)return{status:"fail",reason:"under_20_minutes",score:0,pool:null};return{status:"fail",reason:"single_topic_over_60",score:0,pool:null};}
async function ensureState(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS collection_state(channel_id TEXT PRIMARY KEY,next_page_token TEXT,status TEXT NOT NULL DEFAULT 'pending',pages_done INTEGER NOT NULL DEFAULT 0,videos_seen INTEGER NOT NULL DEFAULT 0,videos_saved INTEGER NOT NULL DEFAULT 0,last_error TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();}

async function resolvePool(env){if(!env.YOUTUBE_API_KEY)throw new Error("YOUTUBE_API_KEY secret is missing");await ensureState(env);await env.DB.prepare("UPDATE channels SET enabled=0,updated_at=CURRENT_TIMESTAMP").run();let quota=0;const resolved=[],unresolved=[];
 for(const c of CHANNEL_POOL){const d=await yt(env,"channels",{part:"snippet,contentDetails",forHandle:c.handle,maxResults:1});quota++;const item=d.items?.[0];if(!item){unresolved.push({name:c.name,handle:c.handle});continue;}const actual=item.snippet?.title||c.name;const uploads=item.contentDetails?.relatedPlaylists?.uploads||null;await env.DB.prepare(`INSERT INTO channels(channel_id,channel_name,category,uploads_playlist_id,source_url,enabled,priority,updated_at) VALUES(?,?,?,?,?,1,?,CURRENT_TIMESTAMP) ON CONFLICT(channel_id) DO UPDATE SET channel_name=excluded.channel_name,category=excluded.category,uploads_playlist_id=COALESCE(excluded.uploads_playlist_id,channels.uploads_playlist_id),source_url=excluded.source_url,enabled=1,priority=excluded.priority,updated_at=CURRENT_TIMESTAMP`).bind(item.id,c.name,c.category,uploads,`https://www.youtube.com/@${c.handle}`,c.priority).run();resolved.push({requested:c.name,youtube_title:actual,channel_id:item.id,handle:c.handle});}
 return{target:CHANNEL_POOL.length,resolved_count:resolved.length,unresolved_count:unresolved.length,resolved,unresolved,quota_units:quota};}

async function startFullSync(env){await ensureState(env);const{results}=await env.DB.prepare("SELECT channel_id FROM channels WHERE enabled=1 ORDER BY priority").all();for(const c of results)await env.DB.prepare(`INSERT INTO collection_state(channel_id,next_page_token,status,pages_done,videos_seen,videos_saved,last_error,updated_at) VALUES(?,NULL,'pending',0,0,0,NULL,CURRENT_TIMESTAMP) ON CONFLICT(channel_id) DO UPDATE SET next_page_token=NULL,status='pending',pages_done=0,videos_seen=0,videos_saved=0,last_error=NULL,updated_at=CURRENT_TIMESTAMP`).bind(c.channel_id).run();return{channels:results.length,status:"ready"};}

async function collectStep(env){await ensureState(env);let row=await env.DB.prepare(`SELECT c.channel_id,c.channel_name,c.category,c.uploads_playlist_id,s.next_page_token,s.pages_done,s.videos_seen,s.videos_saved FROM channels c JOIN collection_state s ON s.channel_id=c.channel_id WHERE c.enabled=1 AND s.status IN ('pending','running','error') ORDER BY c.priority LIMIT 1`).first();if(!row)return{done:true,message:"all enabled channels completed",quota_units:0};if(!row.uploads_playlist_id)throw new Error(`uploads playlist missing: ${row.channel_name}`);await env.DB.prepare("UPDATE collection_state SET status='running',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE channel_id=?").bind(row.channel_id).run();let quota=0;
 try{const p={part:"contentDetails",playlistId:row.uploads_playlist_id,maxResults:50};if(row.next_page_token)p.pageToken=row.next_page_token;const list=await yt(env,"playlistItems",p);quota++;const ids=(list.items||[]).map(x=>x.contentDetails?.videoId).filter(Boolean);let saved=0;if(ids.length){const d=await yt(env,"videos",{part:"snippet,contentDetails,statistics",id:ids.join(","),maxResults:50});quota++;const stm=[];for(const v of d.items||[]){const s=v.snippet||{},st=v.statistics||{},seconds=parseDuration(v.contentDetails?.duration),g=gate(s.title,seconds,row.category);stm.push(env.DB.prepare(`INSERT INTO videos(video_id,channel_id,title,description,published_at,duration_seconds,thumbnail_url,view_count,like_count,gate_status,gate_reason,listen_score,time_pool,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(video_id) DO UPDATE SET title=excluded.title,description=excluded.description,published_at=excluded.published_at,duration_seconds=excluded.duration_seconds,thumbnail_url=excluded.thumbnail_url,view_count=excluded.view_count,like_count=excluded.like_count,gate_status=excluded.gate_status,gate_reason=excluded.gate_reason,listen_score=excluded.listen_score,time_pool=excluded.time_pool,updated_at=CURRENT_TIMESTAMP`).bind(v.id,row.channel_id,s.title||"",s.description||"",s.publishedAt||new Date(0).toISOString(),seconds,s.thumbnails?.medium?.url||s.thumbnails?.default?.url||null,Number(st.viewCount||0),Number(st.likeCount||0),g.status,g.reason,g.score,g.pool));saved++;}if(stm.length)await env.DB.batch(stm);}
 const done=!list.nextPageToken;await env.DB.prepare(`UPDATE collection_state SET next_page_token=?,status=?,pages_done=pages_done+1,videos_seen=videos_seen+?,videos_saved=videos_saved+?,updated_at=CURRENT_TIMESTAMP WHERE channel_id=?`).bind(list.nextPageToken||null,done?'completed':'running',ids.length,saved,row.channel_id).run();if(done)await env.DB.prepare("UPDATE channels SET last_collected_at=CURRENT_TIMESTAMP WHERE channel_id=?").bind(row.channel_id).run();return{done:false,channel:row.channel_name,page:Number(row.pages_done)+1,page_items:ids.length,saved,channel_completed:done,quota_units:quota,next:done?"next channel":"next page"};
 }catch(e){await env.DB.prepare("UPDATE collection_state SET status='error',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE channel_id=?").bind(String(e?.message||e),row.channel_id).run();throw e;}}

async function status(env){await ensureState(env);const{results}=await env.DB.prepare(`SELECT c.channel_name,c.category,c.enabled,s.status,s.pages_done,s.videos_seen,s.videos_saved,s.last_error FROM channels c LEFT JOIN collection_state s ON s.channel_id=c.channel_id ORDER BY c.priority`).all();const v=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN gate_status='pass' THEN 1 ELSE 0 END) passed,SUM(CASE WHEN gate_reason='long_play_compilation' THEN 1 ELSE 0 END) long_play FROM videos").first();return{channels:results,videos:v};}

export default{async fetch(request,env){const u=new URL(request.url);try{if(u.pathname==="/api/health")return json({ok:true,service:"CONTEXT Video",version:"0.5.1",stage:"15-channel-full-history"});if(u.pathname==="/api/pool/resolve")return json({ok:true,...await resolvePool(env)});if(u.pathname==="/api/collect/start")return json({ok:true,...await startFullSync(env),quota_units_used:0});if(u.pathname==="/api/collect/step")return json({ok:true,...await collectStep(env)});if(u.pathname==="/api/collect/status")return json({ok:true,...await status(env)});if(u.pathname==="/api/channels"){const{results}=await env.DB.prepare("SELECT channel_id,channel_name,category,enabled,priority,last_collected_at FROM channels ORDER BY priority").all();return json({ok:true,channels:results});}return json({service:"CONTEXT Video",version:"0.5.1",message:"15-channel registry + resumable full-history collector",endpoints:["GET /api/pool/resolve","GET /api/collect/start","GET /api/collect/step","GET /api/collect/status"]});}catch(e){return json({ok:false,reason:String(e?.message||e)},500);}},async scheduled(controller,env){try{await collectStep(env);}catch(e){console.error("scheduled collection failed",String(e?.message||e));}}};
